// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `rdl2ot` containing data structure

package uart_reg_pkg;

  // Param list

  // Address widths within the block
  parameter int RegsAw = 6;

  // Number of registers for every interface
  parameter int NumRegsRegs = 13;

  ///////////////////////////////////////////////
  // Typedefs for registers for regs interface //
  ///////////////////////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } tx_watermark;
    struct packed {
      logic        q;
      logic        qe;
    } rx_watermark;
    struct packed {
      logic        q;
      logic        qe;
    } tx_empty;
    struct packed {
      logic        q;
      logic        qe;
    } rx_overflow;
    struct packed {
      logic        q;
      logic        qe;
    } rx_frame_err;
    struct packed {
      logic        q;
      logic        qe;
    } rx_break_err;
    struct packed {
      logic        q;
      logic        qe;
    } rx_timeout;
    struct packed {
      logic        q;
      logic        qe;
    } rx_parity_err;
  } uart_reg2hw_interrupt_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } tx_watermark;
    struct packed {
      logic        q;
      logic        qe;
    } rx_watermark;
    struct packed {
      logic        q;
      logic        qe;
    } tx_empty;
    struct packed {
      logic        q;
      logic        qe;
    } rx_overflow;
    struct packed {
      logic        q;
      logic        qe;
    } rx_frame_err;
    struct packed {
      logic        q;
      logic        qe;
    } rx_break_err;
    struct packed {
      logic        q;
      logic        qe;
    } rx_timeout;
    struct packed {
      logic        q;
      logic        qe;
    } rx_parity_err;
  } uart_reg2hw_interrupt_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } tx_watermark;
    struct packed {
      logic        q;
      logic        qe;
    } rx_watermark;
    struct packed {
      logic        q;
      logic        qe;
    } tx_empty;
    struct packed {
      logic        q;
      logic        qe;
    } rx_overflow;
    struct packed {
      logic        q;
      logic        qe;
    } rx_frame_err;
    struct packed {
      logic        q;
      logic        qe;
    } rx_break_err;
    struct packed {
      logic        q;
      logic        qe;
    } rx_timeout;
    struct packed {
      logic        q;
      logic        qe;
    } rx_parity_err;
  } uart_reg2hw_interrupt_test_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } uart_reg2hw_alert_test_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } tx;
    struct packed {
      logic        q;
      logic        qe;
    } rx;
    struct packed {
      logic        q;
      logic        qe;
    } nf;
    struct packed {
      logic        q;
      logic        qe;
    } slpbk;
    struct packed {
      logic        q;
      logic        qe;
    } llpbk;
    struct packed {
      logic        q;
      logic        qe;
    } parity_en;
    struct packed {
      logic        q;
      logic        qe;
    } parity_odd;
    struct packed {
      logic [1:0]  q;
      logic        qe;
    } rxblvl;
    struct packed {
      logic [15:0] q;
      logic        qe;
    } nco;
  } uart_reg2hw_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } txfull;
    struct packed {
      logic        q;
      logic        qe;
    } rxfull;
    struct packed {
      logic        q;
      logic        qe;
    } txempty;
    struct packed {
      logic        q;
      logic        qe;
    } txidle;
    struct packed {
      logic        q;
      logic        qe;
    } rxidle;
    struct packed {
      logic        q;
      logic        qe;
    } rxempty;
  } uart_reg2hw_status_reg_t;

  typedef struct packed {
    logic [7:0]  q;
    logic        qe;
  } uart_reg2hw_rdata_reg_t;

  typedef struct packed {
    logic [7:0]  q;
    logic        qe;
  } uart_reg2hw_wdata_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } rxrst;
    struct packed {
      logic        q;
      logic        qe;
    } txrst;
    struct packed {
      logic [2:0]  q;
      logic        qe;
    } rxilvl;
    struct packed {
      logic [1:0]  q;
      logic        qe;
    } txilvl;
  } uart_reg2hw_fifo_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic [5:0]  q;
      logic        qe;
    } txlvl;
    struct packed {
      logic [5:0]  q;
      logic        qe;
    } rxlvl;
  } uart_reg2hw_fifo_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } txen;
    struct packed {
      logic        q;
      logic        qe;
    } txval;
  } uart_reg2hw_ovrd_reg_t;

  typedef struct packed {
    logic [15:0] q;
    logic        qe;
  } uart_reg2hw_val_reg_t;

  typedef struct packed {
    struct packed {
      logic [23:0] q;
      logic        qe;
    } val;
    struct packed {
      logic        q;
      logic        qe;
    } en;
  } uart_reg2hw_timeout_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } tx_watermark;
    struct packed {
      logic        d;
    } rx_watermark;
    struct packed {
      logic        d;
    } tx_empty;
    struct packed {
      logic        d;
    } rx_overflow;
    struct packed {
      logic        d;
    } rx_frame_err;
    struct packed {
      logic        d;
    } rx_break_err;
    struct packed {
      logic        d;
    } rx_timeout;
    struct packed {
      logic        d;
    } rx_parity_err;
  } uart_hw2reg_interrupt_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } tx_watermark;
    struct packed {
      logic        d;
    } rx_watermark;
    struct packed {
      logic        d;
    } tx_empty;
    struct packed {
      logic        d;
    } rx_overflow;
    struct packed {
      logic        d;
    } rx_frame_err;
    struct packed {
      logic        d;
    } rx_break_err;
    struct packed {
      logic        d;
    } rx_timeout;
    struct packed {
      logic        d;
    } rx_parity_err;
  } uart_hw2reg_interrupt_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } tx_watermark;
    struct packed {
      logic        d;
    } rx_watermark;
    struct packed {
      logic        d;
    } tx_empty;
    struct packed {
      logic        d;
    } rx_overflow;
    struct packed {
      logic        d;
    } rx_frame_err;
    struct packed {
      logic        d;
    } rx_break_err;
    struct packed {
      logic        d;
    } rx_timeout;
    struct packed {
      logic        d;
    } rx_parity_err;
  } uart_hw2reg_interrupt_test_reg_t;

  typedef struct packed {
    logic        d;
  } uart_hw2reg_alert_test_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } tx;
    struct packed {
      logic        d;
    } rx;
    struct packed {
      logic        d;
    } nf;
    struct packed {
      logic        d;
    } slpbk;
    struct packed {
      logic        d;
    } llpbk;
    struct packed {
      logic        d;
    } parity_en;
    struct packed {
      logic        d;
    } parity_odd;
    struct packed {
      logic [1:0]  d;
    } rxblvl;
    struct packed {
      logic [15:0] d;
    } nco;
  } uart_hw2reg_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } txfull;
    struct packed {
      logic        d;
    } rxfull;
    struct packed {
      logic        d;
    } txempty;
    struct packed {
      logic        d;
    } txidle;
    struct packed {
      logic        d;
    } rxidle;
    struct packed {
      logic        d;
    } rxempty;
  } uart_hw2reg_status_reg_t;

  typedef struct packed {
    logic [7:0]  d;
  } uart_hw2reg_rdata_reg_t;

  typedef struct packed {
    logic [7:0]  d;
  } uart_hw2reg_wdata_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } rxrst;
    struct packed {
      logic        d;
    } txrst;
    struct packed {
      logic [2:0]  d;
    } rxilvl;
    struct packed {
      logic [1:0]  d;
    } txilvl;
  } uart_hw2reg_fifo_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic [5:0]  d;
    } txlvl;
    struct packed {
      logic [5:0]  d;
    } rxlvl;
  } uart_hw2reg_fifo_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } txen;
    struct packed {
      logic        d;
    } txval;
  } uart_hw2reg_ovrd_reg_t;

  typedef struct packed {
    logic [15:0] d;
  } uart_hw2reg_val_reg_t;

  typedef struct packed {
    struct packed {
      logic [23:0] d;
    } val;
    struct packed {
      logic        d;
    } en;
  } uart_hw2reg_timeout_ctrl_reg_t;

  // Register -> HW type for regs interface
  typedef struct packed {
    uart_reg2hw_interrupt_state_reg_t interrupt_state;
    uart_reg2hw_interrupt_enable_reg_t interrupt_enable;
    uart_reg2hw_interrupt_test_reg_t interrupt_test;
    uart_reg2hw_alert_test_reg_t alert_test;
    uart_reg2hw_ctrl_reg_t ctrl;
    uart_reg2hw_status_reg_t status;
    uart_reg2hw_rdata_reg_t rdata;
    uart_reg2hw_wdata_reg_t wdata;
    uart_reg2hw_fifo_ctrl_reg_t fifo_ctrl;
    uart_reg2hw_fifo_status_reg_t fifo_status;
    uart_reg2hw_ovrd_reg_t ovrd;
    uart_reg2hw_val_reg_t val;
    uart_reg2hw_timeout_ctrl_reg_t timeout_ctrl;
  } uart_regs_reg2hw_t;

  // HW -> register type for regs interface
  typedef struct packed {
    uart_hw2reg_interrupt_state_reg_t interrupt_state;
    uart_hw2reg_interrupt_enable_reg_t interrupt_enable;
    uart_hw2reg_interrupt_test_reg_t interrupt_test;
    uart_hw2reg_alert_test_reg_t alert_test;
    uart_hw2reg_ctrl_reg_t ctrl;
    uart_hw2reg_status_reg_t status;
    uart_hw2reg_rdata_reg_t rdata;
    uart_hw2reg_wdata_reg_t wdata;
    uart_hw2reg_fifo_ctrl_reg_t fifo_ctrl;
    uart_hw2reg_fifo_status_reg_t fifo_status;
    uart_hw2reg_ovrd_reg_t ovrd;
    uart_hw2reg_val_reg_t val;
    uart_hw2reg_timeout_ctrl_reg_t timeout_ctrl;
  } uart_regs_hw2reg_t;

  // Register offsets for regs interface
  parameter logic [RegsAw-1:0] UART_INTERRUPT_STATE_OFFSET = 6'h 0;
  parameter logic [RegsAw-1:0] UART_INTERRUPT_ENABLE_OFFSET = 6'h 4;
  parameter logic [RegsAw-1:0] UART_INTERRUPT_TEST_OFFSET = 6'h 8;
  parameter logic [RegsAw-1:0] UART_ALERT_TEST_OFFSET = 6'h c;
  parameter logic [RegsAw-1:0] UART_CTRL_OFFSET = 6'h 10;
  parameter logic [RegsAw-1:0] UART_STATUS_OFFSET = 6'h 14;
  parameter logic [RegsAw-1:0] UART_RDATA_OFFSET = 6'h 18;
  parameter logic [RegsAw-1:0] UART_WDATA_OFFSET = 6'h 1c;
  parameter logic [RegsAw-1:0] UART_FIFO_CTRL_OFFSET = 6'h 20;
  parameter logic [RegsAw-1:0] UART_FIFO_STATUS_OFFSET = 6'h 24;
  parameter logic [RegsAw-1:0] UART_OVRD_OFFSET = 6'h 28;
  parameter logic [RegsAw-1:0] UART_VAL_OFFSET = 6'h 2c;
  parameter logic [RegsAw-1:0] UART_TIMEOUT_CTRL_OFFSET = 6'h 30;

  // Reset values for hwext registers and their fields for regs interface

  // Register index for regs interface
  typedef enum int {
    UART_INTERRUPT_STATE,
    UART_INTERRUPT_ENABLE,
    UART_INTERRUPT_TEST,
    UART_ALERT_TEST,
    UART_CTRL,
    UART_STATUS,
    UART_RDATA,
    UART_WDATA,
    UART_FIFO_CTRL,
    UART_FIFO_STATUS,
    UART_OVRD,
    UART_VAL,
    UART_TIMEOUT_CTRL
  } uart_regs_id_e;

  // Register width information to check illegal writes for regs interface
  parameter logic [3:0] UART_REGS_PERMIT [13] = '{
    4'b 0001, // index[ 0] UART_INTERRUPT_STATE
    4'b 0001, // index[ 1] UART_INTERRUPT_ENABLE
    4'b 0001, // index[ 2] UART_INTERRUPT_TEST
    4'b 0001, // index[ 3] UART_ALERT_TEST
    4'b 1111, // index[ 4] UART_CTRL
    4'b 0001, // index[ 5] UART_STATUS
    4'b 0001, // index[ 6] UART_RDATA
    4'b 0001, // index[ 7] UART_WDATA
    4'b 0001, // index[ 8] UART_FIFO_CTRL
    4'b 0101, // index[ 9] UART_FIFO_STATUS
    4'b 0001, // index[10] UART_OVRD
    4'b 0011, // index[11] UART_VAL
    4'b 1111  // index[12] UART_TIMEOUT_CTRL
  };

endpackage